language: r
sudo: false
latex: true
r:
  - release

git:
  submodules: false

warnings_are_errors: true
env:
  global:
    - _R_CHECK_CRAN_INCOMING_=FALSE
    - secure: "y6dn6JypVJq42dKJLqBT5WGiezaLjx27REgEECM1+pGzxmhAzmHDQtlHXYTIMZeqjV7eyDJm1FTEct/DPvuuO5okk9IqWPtM0NDkhaDhC27y5+BhE1VubAq0HkXAK4kwJ61jGY2hi+6YTasmwOyYA9bdSMfh9giFQVFGCqSUW4Q="
    - secure: wAD2PyxJ8IdG4c4kh2fBbwaK8W8JTkAoVsK3ehH4yzUS5qYtctWhczmru34iWt+NxKzZGYqLyg7OPU0hPwgn8OUexUzHc7Yamms++5UObHklwkDqGfJXX+xKHv3AmgRwfjaBulWusNn7q6swn0Bl4j0dDiyD1o7Mz1VYtVUOOaU=

r_github_packages:
  - r-lib/covr
  - RcppCore/Rcpp

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "r-simmer/simmer"
      description: "Build submitted via Travis CI"
    notification_email: iucar@fedoraproject.org
    build_command: "R CMD INSTALL --no-R --no-data --no-help --no-demo --no-inst --no-docs --no-exec --no-multiarch --no-test-load --preclean ."
    branch_pattern: coverity_scan
